### ISSUE TITLE
更换base model报错 RuntimeError: mat1 and mat2 shapes cannot be multiplied (856x768 and 1024x256)

### ISSUE THREAD

**Issue by lichuanxiang** [xhw205/GPLinker_torch#17]
![image](https://user-images.githubusercontent.com/10071850/223934274-13312fdb-a2af-40ee-8879-ff9506833c43.png)

看之前有开过一个帖子（https://github.com/xhw205/GPLinker_torch/issues/7），但没下文了，辛苦帮看下，是因为转换为其他 base model 需要做特殊处理吗？

**Comment by lichuanxiang** [comment]
主要改动：
`from transformers import BertTokenizerFast, BertModel, AutoTokenizer, AutoModel`
`tokenizer = AutoTokenizer.from_pretrained("nghuyong/ernie-health-zh")`
`encoder = AutoModel.from_pretrained("nghuyong/ernie-health-zh")`

**Comment by ExcaliburPro** [comment]
您好，请问我用的BERT，按照这样改还是报错的，是只能用roberta吗
