### ISSUE TITLE
似乎有个BUG，训练过程loss出现负值，但是保存的模型仍然有效

### ISSUE THREAD

**Issue by xhw205** [xhw205/GPLinker_torch#3]
有知道原因的朋友欢迎讨论

**Comment by xhw205** [comment]
https://github.com/bojone/bert4keras/issues/436

**Comment by Chtholly1** [comment]
确实是的，我也没搞太明白，不过还是复现的很赞了，感谢作者！

**Comment by touchwolf** [comment]
> [bojone/bert4keras#436](https://github.com/bojone/bert4keras/issues/436)

仔细调试了一下，苏神在截断的时候采用的值是1e-7，而楼主复现的代码里截断值是1e-10，会不会是这个原因？
